import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/common/Header";
import localFont from 'next/font/local'
import "./globals.css";

const nanumSquareNeo = localFont({
  src: './fonts/NanumSquareNeo-Variable.woff2', // 파일 경로
  variable: '--font-nanum', // CSS 변수명 정의
  display: 'swap',
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Codeit Project",
  description: "Generated by An",
  icons: {
    icon: {
      url: '/img/do_it-mobile.svg',
      type: 'image/svg+xml',
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nanumSquareNeo.variable} font-sans`}
      >
        <Header />
        <main className="max-w-[1200px] mx-auto w-full px-4 min-w-[375px] overflow-x-auto">
          {children}
        </main>
        
      </body>
    </html>
  );
}
